// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using PullRequestsViewer.SqlLite;
using System;

namespace PullRequestsViewer.SqlLite.Migrations
{
    [DbContext(typeof(PullRequestsViewerContext))]
    partial class PullRequestsViewerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-preview2-25794");

            modelBuilder.Entity("PullRequestsViewer.Domain.Repository", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OwnerLogin");

                    b.HasKey("Name");

                    b.ToTable("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
